language: android

jdk: oraclejdk8

sudo: false

android:
  components:
    - platform-tools
    - tools
    - build-tools-27.0.3
    - android-24
    - android-27
    - sys-img-armeabi-v7a-android-24
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support
    - extra-google-google_play_services

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  #- cp ./google-licenses/* "$ANDROID_HOME/licenses/"
  - chmod +x gradlew

script:
    - ./gradlew build connectedCheck

#deploy:
#  provider: bintray
#  file: "descriptor.json"
#  user: $BINTRAY_USER
#  key: $BINTRAY_API_KEY
#  skip_cleanup: true # to upload artifacts created during the build
#  dry-run: false
#  on: production